#!/usr/bin/env python3
"""Generate the fheroes2 Korean prototype bitmap font header from Galmuri11."""
from __future__ import annotations

import argparse
import base64
import struct
import zlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

HANGUL_FIRST = 0xAC00
HANGUL_COUNT = 11172


def build_rows(font_path: Path, point_size: int, width: int, height: int) -> bytes:
    font = ImageFont.truetype(str(font_path), point_size)
    output = bytearray()

    for codepoint in range(HANGUL_FIRST, HANGUL_FIRST + HANGUL_COUNT):
        ch = chr(codepoint)
        image = Image.new("L", (width, height), 0)
        draw = ImageDraw.Draw(image)
        bbox = font.getbbox(ch)
        x = -bbox[0]
        y = -bbox[1]
        draw.text((x, y), ch, font=font, fill=255)

        pixels = image.load()
        for row_y in range(height):
            bits = 0
            for x_pos in range(width):
                if pixels[x_pos, row_y] >= 128:
                    bits |= 1 << x_pos
            output.extend(struct.pack("<I", bits))

    return bytes(output)


def quoted_chunks(value: str, width: int = 120) -> str:
    return "\n".join(f'    "{value[i:i+width]}"' for i in range(0, len(value), width))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("font", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    specs = [
        ("small", 9, 9, 10),
        ("normal", 11, 11, 11),
        # Large Korean text uses Galmuri in the first full-text prototype.
        # The decorative Solmoe KimDaeGeon path stays a separate follow-up.
        ("large", 22, 22, 24),
    ]

    blocks: list[str] = []
    blocks.append("// Generated by script/generate_korean_font.py. Do not edit.\n#pragma once\n\n#include <cstddef>\n#include <string_view>\n\nnamespace fheroes2::koreanFontGenerated\n{")

    for name, point_size, width, height in specs:
        raw = build_rows(args.font, point_size, width, height)
        encoded = base64.b64encode(zlib.compress(raw, 9)).decode("ascii")
        blocks.append(f"    inline constexpr int {name}Width = {width};")
        blocks.append(f"    inline constexpr int {name}Height = {height};")
        blocks.append(f"    inline constexpr int {name}Advance = {width};")
        blocks.append(f"    inline constexpr std::size_t {name}RawSize = {len(raw)};")
        blocks.append(f"    inline constexpr std::string_view {name}Base64 =\n{quoted_chunks(encoded)};")

    blocks.append("}\n")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(blocks), encoding="utf-8")


if __name__ == "__main__":
    main()
