#!/usr/bin/env python3
"""Generate compressed bitmap glyph data for the UTF-8 large-alphabet provider."""
from __future__ import annotations

import argparse
import base64
import struct
import zlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

HANGUL_FIRST = 0xAC00
HANGUL_LAST = 0xD7A3


def collect_codepoints(po_path: Path | None, include_hangul: bool) -> list[int]:
    codepoints: set[int] = set()

    if include_hangul:
        codepoints.update(range(HANGUL_FIRST, HANGUL_LAST + 1))

    if po_path is not None:
        import polib

        po = polib.pofile(str(po_path), encoding="utf-8")
        for entry in po:
            translated: list[str] = []
            if entry.msgstr:
                translated.append(entry.msgstr)
            translated.extend(value for value in entry.msgstr_plural.values() if value)

            for text in translated:
                for ch in text:
                    codepoint = ord(ch)
                    # ASCII continues to use the stock fheroes2 bitmap fonts.
                    if codepoint >= 0x80 and ch not in "\r\n\t":
                        codepoints.add(codepoint)

    return sorted(codepoints)


def build_rows(font_path: Path, codepoints: list[int], point_size: int, width: int, height: int) -> bytes:
    font = ImageFont.truetype(str(font_path), point_size)
    output = bytearray()

    for codepoint in codepoints:
        ch = chr(codepoint)

        # Galmuri is a pixel font. Render directly to a 1-bit target to keep
        # the original pixel grid instead of thresholding an antialiased image.
        image = Image.new("1", (width, height), 0)
        draw = ImageDraw.Draw(image)
        bbox = font.getbbox(ch)
        x = -bbox[0]
        y = -bbox[1]
        draw.text((x, y), ch, font=font, fill=1, stroke_width=0)

        pixels = image.load()
        for row_y in range(height):
            bits = 0
            for x_pos in range(width):
                if pixels[x_pos, row_y]:
                    bits |= 1 << x_pos
            output.extend(struct.pack("<I", bits))

    return bytes(output)


def quoted_chunks(value: str, width: int = 120) -> str:
    return "\n".join(f'    "{value[i:i + width]}"' for i in range(0, len(value), width))


def codepoint_chunks(codepoints: list[int], per_line: int = 12) -> str:
    lines: list[str] = []
    for i in range(0, len(codepoints), per_line):
        values = ", ".join(f"0x{value:04X}U" for value in codepoints[i:i + per_line])
        lines.append(f"        {values},")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("font", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--po", type=Path, default=None, help="Also include all non-ASCII code points used by translated strings in this PO file.")
    parser.add_argument("--include-hangul", action="store_true", help="Include every modern precomposed Hangul syllable (U+AC00..U+D7A3).")
    args = parser.parse_args()

    codepoints = collect_codepoints(args.po, args.include_hangul)
    if not codepoints:
        raise SystemExit("No large-alphabet code points were selected.")

    # Galmuri11's native 12 px cell is used for small/normal UI text. Large
    # text is an exact 2x integer scale so the pixel grid stays crisp.
    specs = [
        ("small", 12, 12, 12),
        ("normal", 12, 12, 12),
        ("large", 24, 24, 24),
    ]

    blocks: list[str] = []
    blocks.append(
        "// Generated by script/generate_large_alphabet_font.py. Do not edit.\n"
        "#pragma once\n\n"
        "#include <array>\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "#include <string_view>\n\n"
        "namespace fheroes2::largeAlphabetGenerated\n"
        "{"
    )
    blocks.append(f"    inline constexpr std::size_t glyphCount = {len(codepoints)};")
    blocks.append("    inline constexpr std::array<uint32_t, glyphCount> codePoints = {\n" + codepoint_chunks(codepoints) + "\n    };")

    for name, point_size, width, height in specs:
        raw = build_rows(args.font, codepoints, point_size, width, height)
        encoded = base64.b64encode(zlib.compress(raw, 9)).decode("ascii")
        blocks.append(f"    inline constexpr int {name}Width = {width};")
        blocks.append(f"    inline constexpr int {name}Height = {height};")
        blocks.append(f"    inline constexpr int {name}Advance = {width};")
        blocks.append(f"    inline constexpr std::size_t {name}RawSize = {len(raw)};")
        blocks.append(f"    inline constexpr std::string_view {name}Base64 =\n{quoted_chunks(encoded)};")

    blocks.append("}\n")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(blocks), encoding="utf-8")

    print(f"Generated {len(codepoints)} glyphs into {args.output}")


if __name__ == "__main__":
    main()
